### ISSUE TITLE
Can't resolve conflicting import

### ISSUE THREAD

**Issue by shacker** [django-extensions/django-extensions#1032]
My app has `people.models.UserProfile`
App Wagtail defines `wagtail.wagtailusers.models.UserProfile`

They clash in `shell_plus` so I always have to manually import my own:

```
from people.models import UserProfile
UserProfile.objects.get(username='shacker')
```

I get errors if I don't do the manual import first:

```
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: approved_notifications, id, rejected_notifications, submitted_notifications, user, user_id
```

I want to solve this with one of the available overrides. I've tried all of these (not at the same time):

```
SHELL_PLUS_MODEL_ALIASES = {'wagtail.wagtailusers': {'UserProfile': 'wt_user_profile'},}
SHELL_PLUS_DONT_LOAD = ['wagtail.wagtailusers', ]
./manage.py shell_plus --dont-load 'wagtail.wagtailusers'
SHELL_PLUS_POST_IMPORTS = [('people.models'), ]
```

In all cases,  accessing `UserProfile.objects.get(username='shacker')` throws the usual error indicating I've got the wrong model. Doing a manual import of my model after shell_plus finishes loading fixes it. 

Am I doing something wrong here, or is there a bug? 

Using python 3.5, django 1.10.5, extensions 1.7.7.7

Thanks.

**Comment by trbs** [comment]
I assume you still see `wagtail.wagtailusers.models.UserProfile` being imported when you start `shell_plus` ?

Could you try it in the style: "%s.%s" % (app_name, model_name) for DONT_LOAD ?

```
SHELL_PLUS_DONT_LOAD = ['wagtailusers.UserProfile', ]
```

or the tuple (package, model_name) for POST_IMPORTS:

```
SHELL_PLUS_POST_IMPORTS = [('people.models', 'UserProfile'), ]
```

(This is from the top of my head)

If this works (otherwise please look at `django_extensions.management.shell`) it's probably not clearly described in the documents. Would you be willing to submit patches to the docs or maybe even patches to the code to make more cases work ?

What I always wanted to have but never had the time to implement is to (also) support the same syntax that Python uses, eg:

```
SHELL_PLUS_DONT_LOAD = [
    'from wagtail.wagtailusers.models import UserProfile', 
]
```

This way it should work by copy-pasting whatever one does in `shell_plus` itself. Using something like AST this should be relatively easily to build. If somebody reading this would have the time to work on that it would be very much appreciated :)

**Comment by shacker** [comment]
Ah! You're right. For app with a nested path, e.g. `wagtail.wagtailusers.models.UserProfile`

This works:
`SHELL_PLUS_DONT_LOAD = ['wagtailusers.UserProfile', ]`

But these do not:
`SHELL_PLUS_DONT_LOAD = ['wagtail.wagtailusers', ]`
`SHELL_PLUS_DONT_LOAD = ['wagtail.wagtailusers.UserProfile', ]`

Yes I'd be happy to add something to the docs on this. Thanks!
