### ISSUE TITLE
embed django-extensions into official django 

### ISSUE THREAD

**Issue by amineparis** [django-extensions/django-extensions#1033]
why do people need to install separately django and django-extensions. If it has +3K stars that means it deserve integration into offictial django framework !!

**Comment by trbs** [comment]
Thanks @amineparis ! Glad you like Django Extensions and that you find it such a great value.

Django Extensions was always meant for things that are not easily included into Django itself and as a testing ground for inclusion.

Although the later rarely happens I admit. If you take a look at two extensions that might be good candidates to include into Django itself like shell_plus and sqldiff, they both need a lot of work and refactoring before they could make it in. Other commands like runserver_plus are not likely for inclusion since they depend on third party packages.

Django Extensions does not adhere to the same rigor as Django although we still strive for quality and stability. This means we can include (or throw out) things sooner / more easily then Django can. It also means that Django does not have to suffer the burden of maintaining these things.

Lastly a lot of the code is meant for development only. The benefit of separate projects is that people can install Django Extensions in development and leave it out of production in most cases.

So I think there is a place for Django Extensions besides Django. 

That said we are always working with Django to make sure Django Extensions is compatible with the latest Django versions and to move extensions into Django itself or if Django maintainers see a need for it move contribs from Django to Django Extensions.
