### ISSUE TITLE
MySQL users will have no alternative when support for JSONField is dropped

### ISSUE THREAD

**Issue by RevolutionTech** [django-extensions/django-extensions#1061]
I noticed that the current docs say the following with respect to `django-extensions`'s `JSONField`:

> Deprecated since version 1.7.3: Django 1.9 features a native JSONField. Django-Extensions will support JSONField at the very least until Django 1.8 becomes unsupported.

Ref: https://django-extensions.readthedocs.io/en/latest/field_extensions.html#current-database-model-field-extensions

However, the `JSONField` provided by Django is for PostgreSQL only.
Ref: https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#jsonfield

Thus, when `django-extensions` drops support for `JSONField`, users of MySQL and other database backends will not have an alternative field that they can migrate to. Shouldn't support for this field be reconsidered?

Thank you for your time!

**Comment by trbs** [comment]
I'm happy to leave it in as long as there are (enough) users that find it useful.

Maybe we should improve the documentation instead of deprecating it. Make it very clear in the docs that alternatives exists like the build-in JSONField when using PostGreSQL and maybe some of the other implementations out there which might be better supported.

Of course everybody is happy to use our version :)

**Comment by RevolutionTech** [comment]
That is great news! Thank you very much for considering leaving it in.

**Comment by trbs** [comment]
Would you like to make a PR for this ?

**Comment by RevolutionTech** [comment]
Sure thing! I'll try to tackle that within the next week.

**Comment by trbs** [comment]
Thanks !
