### ISSUE TITLE
jupyter lab

### ISSUE THREAD

**Issue by strelnikov** [django-extensions/django-extensions#1104]
please consider jupyter lab for shell_plus ;)

**Comment by trbs** [comment]
I would love to be able to support JupyterLab !
(and in general improve our Jupyter notebook support)

PR's are most welcome !

**Comment by bhrutledge** [comment]
@strelnikov Here's a temporary workaround:

Assuming you've run `manage.py shell_plus --notebook` at least once, you can [install JupyterLab](https://github.com/jupyterlab/jupyterlab#installation) in your virtual environment, and then just run `jupyter lab`. You should be able to create new "Django Shell-Plus" notebooks, and run existing ones. This works because `shell_plus --notebook` installs a Jupyter kernel, which is left in place even after you kill `shell_plus`.

**Comment by bhrutledge** [comment]
As I understand it, this is a request for something like `manage.py shell_plus --lab`.

Another way to approach this would be to encourage folks to install Jupyter notebook/lab/etc. into a separate environment, and then have a new management command for installing a kernel for the current Django environment. This seems to follow the recommendation from the [IPython docs](https://ipython.readthedocs.io/en/latest/install/kernel_install.html#kernels-for-different-environments). I think the behavior would be similar to `python -m ipykernel install --user --name myvenv`, but with a kernel spec that has an `argv` similar to the current `shell_plus --notebook`.

FWIW, I have a repo for my base Jupyter environment, with instructions on how to add kernels for other environments: https://github.com/bhrutledge/jupyter-venv. The advantage of this approach is that it avoids cluttering up the Django environment with all of Jupyter's dependencies, and means you only have to have one notebook/lab instance running. Of course, the current approach of `shell_plus --notebook` is probably easier for people who haven't used Jupyter before.

**Comment by jdmold** [comment]
@n1-cz if you want something quick and dirty install jupyter lab, run `manage.py shell_plus --notebook`. Then open the notebook url, get the sign in out of the way, and go to `/lab`. You'll see the django shell in launcher, I've used it a bit everything seems to work.

Lets say I'm running `docker-compose run django-container -p 36000:8888 manage.py shell_plus --notebook` after taking care of the token stuff I then go to `localhost:36000/lab` and bask in the goodness.

![screen shot 2018-10-26 at 3 35 55 pm](https://user-images.githubusercontent.com/7205787/47591343-df23eb00-d934-11e8-99c7-8d31c10cc71f.png)

**Comment by kgang** [comment]
I'd like to make a pull request for this, adding a --lab option. Should be able to grab LabApp rather than NotebookApp in get_notebook() and keep the rest of the flow the same since LabApp inherits NotebookApp in JupyterLab's code. Think I'll parameterize get_notebook() and run_notebook() with a flag lab=False.

Does that sound ok @trbs?

**Comment by trbs** [comment]
@kgang yes !

**Comment by terencehonles** [comment]
> I'd like to make a pull request for this, adding a --lab option. Should be able to grab LabApp rather than NotebookApp in get_notebook() and keep the rest of the flow the same since LabApp inherits NotebookApp in JupyterLab's code. Think I'll parameterize get_notebook() and run_notebook() with a flag lab=False.
> 
> Does that sound ok @trbs?

@kgang I was already touching this code, and figured it would be easy for me to update my PR, I split it out into its own PR (#1513) in case they should be reviewed independently.
