### ISSUE TITLE
When generating a 'graphic_model' M2M fields are missing.

### ISSUE THREAD

**Issue by cnobile2012** [django-extensions/django-extensions#1139]
When I run the command:

```
./manage.py graph_models -ago docs/<filename>.png
```
All many to many fields are missing. I have tried both pygraphviz or pydot and although the generated file size is a bit different, neither made any difference with the M2M fields.

I'm using version: 1.9.8

**Comment by jrd** [comment]
Works ok for me. If A has a M2M field to B, I have the link from A to B with the relations along the link.

If a `through AB` is indicated (because some data should be kept in the A-B relation, the table is shown and two links appear.

Be careful, the command is `graph_models`, not `graph_database_tables`!!

The only thing that could be improved is the information displayed along the links. It will be better to say `bs from a` rather than `bs (a)`.

The link could also be oriented if the access is possible only in one way.

But all in all. I think this issue could be closed because there is no bug.

**Comment by trbs** [comment]
@jrd you want to make another issue for the improvements you outlined ?
