### ISSUE TITLE
shell_plus - import all subclasses

### ISSUE THREAD

**Issue by domandinho** [django-extensions/django-extensions#1158]
I want to load all classes of my project which are subclasses of some class into shell_plus.
It is very useful for example if we have model factories from 
https://github.com/FactoryBoy/factory_boy
or if we want to preload serializers
(
not-generic version of this is requested in this ticket: https://github.com/django-extensions/django-extensions/issues/1013
)

Base classes will be set by this option:
```
SHELL_PLUS_SUBCLASSES_IMPORT = 
[
	'factory.django.DjangoModelFactory'
]
```
by passing `List[Union[Type, str]]`

With this setting shell_plus should find all subclasses of DjangoModelFactory in project and load them.
Is this feature is acceptable?
I want to implement this feature and submit PR if it is.

**Comment by trbs** [comment]
Yes happy to, specially if we can also close ticket like #1013 in a more generic way.

Little bit of background thoughts:

Hesitated a little bit since I think the current way of defining the imports feels really clunky to me.. and I would prefer not to add to it. Instead I still hope to someday implement something like https://github.com/django-extensions/django-extensions/pull/867#issuecomment-214680638 :-)

But that won't solve automatic loading of all classes that are subclasses of some Type. In itself this option seems pretty clean way of doing so. So happy to accept a PR for the generic way of doing so :-)

**Comment by domandinho** [comment]
https://github.com/django-extensions/django-extensions/pull/1160

**Comment by trbs** [comment]
Thanks !
