### ISSUE TITLE
Back again: exec in subfunction = syntaxerror

### ISSUE THREAD

**Issue by joej** [django-extensions/django-extensions#1166]
Same as previous error (bug report, then fix), which was fixed.
shell_plus.py ... the exec()  near line number 230:

_./manage.py shell_plus --use-pythonrc_
File "/xxx/lib/python2.7/django_extensions/management/commands/shell_plus.py", line 230, in get_plain
exec(compile(handle.read(), pythonrc, 'exec'), imported_objects) in globals(), locals()
TypeError: exec: arg 1 must be a string, file, or code object

**New solution:**
`                        execfile(pythonrc) in globals(), locals()`

works for me

**Comment by trbs** [comment]
We really need a test case for this...

Could you try to make a PR for a test case ?

**Comment by trbs** [comment]
Commited 50a0e4c this makes `django-extensions` follow the exact same code as that `Django` uses.

This removes the fix for a bug in `Python` versions below 2.7.9, which might now break again. However since 2.7.9 was released 4 years ago I feel it's better to not break recent versions of Python 2.7.x then having the old ones work.
