### ISSUE TITLE
Shell plus crash 

### ISSUE THREAD

**Issue by anuranjit** [django-extensions/django-extensions#1184]
Scenario 
1: Class A  
```
class A(models.Model): 
   m2m = models.ManyToManyField(B)
```
2: Class B
```
class B(models.Model):
   a = models.IntegerField() #Irrelevant to the problem
```
3. Class C
```
class C(models.Model):
   b  = models.IntegerField()
   class Meta:
      db_table = "a_m2m" # Same as the of the intermediate many to many table created by django For **m2m** field in Model A
```

Try opening `./manage.py shell_plus`. It Crashes, `./manage.py shell` on the other hand works

Is this expected ?

**Comment by trbs** [comment]
It does not crash for me. I get a helpful error message:

```
$ ./manage.py shell_plus
SystemCheckError: System check identified some issues:

ERRORS:
testapp.A.m2m: (fields.E303) Reverse query name for 'A.m2m' clashes with field name 'B.a'.
	HINT: Rename field 'B.a', or add/change a related_name argument to the definition for field 'A.m2m'.
```

Which makes sense in this case I think. Since we want to import these models and it would lead to unexpected results if we did not let Django check for these errors.

If you got another problem and `shell_plus` really crashed for you then please post the output of `shell_plus` and reopen the ticket. Otherwise I think this is indeed `expected` and correct.

**Comment by anuranjit** [comment]
@trbs  Sorry, got the error, but apparently it got lost in a lot of warnings in my project. Thanks.

**Comment by trbs** [comment]
No problem thanks for the report ! Might also help others in the future when they google the error 👍
