### ISSUE TITLE
runscript should exit with non-zero status code when no module found

### ISSUE THREAD

**Issue by alexmuller** [django-extensions/django-extensions#1185]
This would be useful for running a script as part of a test suite, for example:

```
python manage.py runscript custom_lint_for_my_app
```

Would you accept a pull request for this?

Questions:

- Could do this by raising `CommandError`, however this prints something. Is this ok when `silent=True`?
- Half a dozen tests would need to change to acknowledge the raising of an error
- Or could also do this by setting the exit code and calling `sys.exit(code)`.

**Comment by trbs** [comment]
Yeah more then happy to accept a PR for this.

Probably `sys.exit` is the easiest way to go ?

**Comment by mick88** [comment]
I have a related issue; if my script fails with an `ImportError`, `runscript` exits with status 0 while it should fail with a proper error code. This is not expected behaviour and should be filed as a bug.

**Comment by mick88** [comment]
I had a look at the code and I'm proposing the following changes:

1.  runscript should differentiate between not being able to import module because the script doesn't exist, not not being able to import because it contains an import error - this will help greatly when debugging scripts
2. runscript command should raise error instead of just printing messages to stdout. Current setup makes it impossible to use it inside a bash script because it does not communicate its exit status correctly. `sys.exit()` proposed above does not fully solve the problem because it interrupts tests (needs to be mocked). In my experience the best way to exit manage.py command is with an error.

I'd be happy enough to implement the above changes if they're approved.

**Comment by trbs** [comment]
@mick88 sounds good !

**Comment by mick88** [comment]
This appears to be resolved as of version 3.0.9. It implements `CommandError()` and returns non-zero status code for any import errors inside the script.

**Comment by trbs** [comment]
Thanks for the update !
