### ISSUE TITLE
[question] When is the next version planned?

### ISSUE THREAD

**Issue by GabLeRoux** [django-extensions/django-extensions#1368]
The current state of master seems good right now. I'm currently using a specific commit to have the #1351 patch. I'm just wondering when will there be a release. There's currently 136 unreleased commits ;)

merged commits related to Issues that would be part of next version:

#1321
#1323
#1325
#1331
#1332
#1335
#1336
#1339
#1341
#1345
#1346
#1347
#1348
#1349
#1350
#1351
#1352
#1353
#1354
#1355
#1356
#1357
#1361
#1363
#1364
#1366

Is there a roadmap?

**Comment by trbs** [comment]
Just uploaded https://pypi.org/project/django-extensions/2.1.7/ to pypi :-)

There is no roadmap or fixed release schedule or alike.

Since I haven't found a way yet to drive some income and therefor dedicate some time for `Django Extensions` the current situation with releases and efforts put into the project will likely not change.
