### ISSUE TITLE
UserPassesTestMixin for currently logged in user

### ISSUE THREAD

**Issue by tdsprogramming** [django-extensions/django-extensions#1392]
I have a mixin I often need to use that is built off `django.contrib.auth.mixins.UserPassesTestMixin` that limits permission of the currently logged in user to only be able to change models that they own. It looks something like this:
```python
class UserPermissionMixin(UserPassesTestMixin):
    def test_func(self):
        current_user = self.request.user
        if current_user == self.model.user:
            return True
        return False
```
Would this be something that I could generalize and submit a pull request for django-extensions?

**Comment by trbs** [comment]
I don't think we have any permissions yet in `django-extensions` :-)

Thinking about it, from personal experience I have a similar mixins which are copied in quite a number of projects. Others probably do the same making it a good candidate to include IMO.

What I would like to see if the ability to change the model attribute. Something like:
```
class UserPermissionMixin(AccessMixin):
    user_permission_model_attribute = "user"

    def get_user_permission_model_attribute(self):
        return self.user_permission_model_attribute

    def test_func(self):
        model_attr = self.get_user_permission_model_attribute()
        current_user = self.request.user
        model_user = getattr(self.model, model_attr)
        current_user = self.request.user

        if current_user == model_user:
            return True

        return False
```

This would allow for more flexibility. eg: you could have a class with an `owner` attribute.
Maybe also add the ability for `user_permission_model_attribute` to be a relationship, such as in the case of model with something like an `attendees` attribute.

Also a similar class for `groups` would make sense :-)

Anyways, I would love to accept a PR for this. Specially if we can make the class generic and easy to use enough that it would appeal to a broad number of users.

Now the only downside to a PR right now is that it would also require some of the boilerplate for things like docs, tests (we should aim for 100% coverage for permission mixins), etc to be written since this is the first permissions extension.

**Comment by tdsprogramming** [comment]
Great! Where would be an appropriate place for this? Since the structure is similar to Django, should it be from `django_extensions.contrib.auth.mixins import UserPermissionMixin`?

**Comment by trbs** [comment]
Think we can skip the `contrib` part and go with `django_extensions.auth.mixins` :-)

**Comment by tdsprogramming** [comment]
I'm writing up the docs, but I'm not comfortable writing tests for django extensions. Can I submit the pull request with docs and source code, and then get an idea for the tests after?

**Comment by tdsprogramming** [comment]
I've got some code ready, but since this is my first contribution to Django Extensions, can I get another eye on it before? I could just submit a PR, but wanted to let you know that it's probably about 50% at this point.

**Comment by trbs** [comment]
sure no problem, happy to take a look, we are very happy with all contributions !

you can submit a PR, attach a patch here or email me (trbs at trbs dot net), all fine by me :-)

**Comment by tdsprogramming** [comment]
I'll submit a PR and go from there. Thanks!

**Comment by anudeepsamaiya** [comment]
can I pick this up?

**Comment by tdsprogramming** [comment]
There is an open Pull Request to just get the finishing touches on it.

**Comment by trbs** [comment]
i'll close the issue and lets finish the PR :-)
