### ISSUE TITLE
Command export_emails not working with custom AUTH_USER_MODEL

### ISSUE THREAD

**Issue by CleitonDeLima** [django-extensions/django-extensions#1431]
Currently the command works with data from standard django model user, today the fixed fields are used `('last_name', 'first_name', 'username', 'email')`.

It would be interesting in cases where the model user is customized with other fields, for example: `('name', 'email')`.

**Comment by trbs** [comment]
https://github.com/django-extensions/django-extensions/commit/baa62556c4da0ee6eeede30f6b9ef32aed88a4ee will allow users to customize the `values()` and `order_by` part of the queryset. 

This should at least give you the option to only query for `('name', 'email')` and not have errors for the missing fields. (`EXPORT_EMAILS_ORDER_BY` and `EXPORT_EMAILS_FIELDS` in `settings.py`)

The `full_name(...)` function can now be overridden (`EXPORT_EMAILS_FULL_NAME_FUNC`) to allow for any custom function to create the `full_name`.

One thing to note is that this allow for people with custom `User` models to use `export_emails` but it does not help putting your custom fields into the output of `export_emails`. Eg: the `vcard` or `outlook` option will not be able to pickup on additional fields like `Job Title` since they currently have no support for it.

I would be happy to accept PR's to extend the current formats (eg: support more fields in outlook, vcard, etc), add support for custom format functions or the ability to customize the queryset and/or provide a mapping dictionary for fields. 

I hope this helps you and other people :-)
