### ISSUE TITLE
The create_app command no longer exists ??

### ISSUE THREAD

**Issue by scwall** [django-extensions/django-extensions#1466]
Hello, I've come across this information:
https://groups.google.com/forum/#!topic/django-developers/_W7qiGl-ThY, I was looking for why urls and forms were not automatically generated by startapp. I could see in this post https://github.com/django-extensions/django-extensions/pull/448 that the command existed at some point. Why this one has been removed ?? is it a bug ?? Personally I find it quite interesting I find it redundant to have to create each time a urls and forms file.  Thanks in advance

**Comment by trbs** [comment]
It was removed in commit https://github.com/django-extensions/django-extensions/commit/8933a16b7d622ba684109befbcdbdcbc7310d293

I must agree in retrospect that this was not clearly explained. For example there is no line in CHANGELOG about the removal other then "removed support for Django versions before 1.11".

The reasoning can be found when diving into the commit above.

Basically it has been marked as deprecated for a while and was not kept up to date with newer Django versions.

Django introduced `startapp --template` back in I think version 1.4 and it has been seen ever since as the preferred way.

Otherwise something like https://cookiecutter.readthedocs.io/ probably provides an even richer experience.

That said; Django-Extensions is about scratching itches and being a lower barrier to enter new code and features in then the Django project itself.

So if there is a good PR with an implementation that provides benefits greater then `startapp --template`, which multiple users want to see included and easier (yeah I know being `easier to use` is all relative :-) ) then something like cookie-cutter I am certainly willing to merge a PR.

**Comment by scwall** [comment]
@trbs thank you very much for the answer
