### ISSUE TITLE
[Suggestion] Create a management command to raise a simple exception for testing error reporters

### ISSUE THREAD

**Issue by YPCrumble** [django-extensions/django-extensions#1503]
I'd love to add a simple management command that raises an exception like:

```
raise Exception("This is a test exception by django-extensions.")
```

It would make testing my error reporting software a lot easier. Would a PR for this be welcomed?

Thanks as always for maintaining this library!!!

**Comment by trbs** [comment]
Yes definitely, I have something similar myself but never included it since I figured I was the only one :-)

Would be nice to create the command such that it allows for (easy) integration with eg the Sentry SDK and a-likes. 

Lastly can I ask to spend a little bit of time to write tests and a few lines of documentation which makes clear what the goal of a command like this is. Think that might help people that otherwise would be confused why this command which errors on purpose exists :-)
