### ISSUE TITLE
shell_plus error when DATABASES OPTIONS set

### ISSUE THREAD

**Issue by BluSpanner** [django-extensions/django-extensions#1570]
shell_plus error when DATABASES OPTIONS set in setting.py

To re-produce...
```
Windows> python manage.py shell_plus
...
... site-packages\django_extensions\management\commands\shell_plus.py", line 472, in set_application_name
     if dbs[db]['ENGINE'] in supported_backends:
KeyError: 'ENGINE'
```

settings.py
```
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        ....
    },
    ...
   "OPTIONS": {"timeout": 20}
```

No error with OPTIONS removed
```
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        ....
    },
    ...
```

**Comment by trbs** [comment]
The `KeyError` is clear :-)

Your defining a database with the name `OPTIONS` and without an `ENGINE` configuration, this is why you get the `KeyError`. You should maybe raise an issue with Django (or better yet a PR) for the documentation. Since I think documentation like https://docs.djangoproject.com/en/3.0/ref/databases/#isolation-level is a bit confusing... AFAIK you cannot set `OPTIONS` as a key in `DATABASES` only on the database itself like:

```python
DATABASES = {
    # ...
    'default': {
        # ...
        'OPTIONS': {
            'isolation_level': psycopg2.extensions.ISOLATION_LEVEL_SERIALIZABLE,
        },
}
```

I committed a patch for `Django Extensions` that will not raise the `KeyError` anymore.
This will be included in the next release.
