### ISSUE TITLE
Django 3.1

### ISSUE THREAD

**Issue by tiagoarasilva** [django-extensions/django-extensions#1574]
I've opened a issue before and it was replied as a non-problem but I ran some tests and with

- Django 2.2.15
- Django Postgres JSONField (not django models as in 3.1)
- Settings installed apps

```python
    'django_nose',
    'django_extensions',
    'debug_toolbar',
    'template_repl',
```

Django shell_plus opens and imports everything but when I change to django 3.1 and django models.JSONField, I can still see the list but it does not import everything and I need to import manually.

At the moment this is the only difference I found so far.... Anyone with the same problem?

UPDATE:

- With `--plain` works fine but with ipython creates a conflict somehow

**Comment by trbs** [comment]
What you are saying is not true. Please read https://github.com/django-extensions/django-extensions/issues/1572 carefully.
It clearly states that we need a reproducible example otherwise we cannot help.

So I am going to give you two options, either you put money on the table and sponsor this work or you need to provide ample information to work on this and expect that other people are doing this in there spare time.

Last but not least, next time when you open an issue make sure the title also reflects the issue. Simple stating "Django x.y" is not helpful to anybody.

If you have something reproducible please re-open this ticket and adjust the title to match.

**Comment by tiagoarasilva** [comment]
@trbs yes yes, I may have expressed myself wrongly, actually it was based on your example that I could see that plain works fine. No worries, I will try to make it more clear next time but I will try to find the reason why which clearly is not the extensions but somewhat a conflict on my project. 

Apologies and thank you

**Comment by trbs** [comment]
It could very well be that `django-extensions` silently swallows some exception somewhere that is the root cause of the issue. If that is the case I would like to fix `shell_plus` in the sense that there should be message displayed to the user. 

But that does also boil down to having a gist or git repo to actually see this issue in action. So if you would be able to make a small project that demonstrates this issue it would be much appreciated.

**Comment by tiagoarasilva** [comment]
Of course I can try but is a hard one to replicate like you mentioned. The workaround that I found was to force ipython to reload by using IPYTHON_ARGUMENTS=['--ext', 'django_extensions.management.notebook_extension'] but I will try to replicate.
