### ISSUE TITLE
ModuleNotFoundError: No module named 'django_extensions'

### ISSUE THREAD

**Issue by WafaaAlhussain** [django-extensions/django-extensions#1618]
I'm having an import error as shown below when I run manage.py check.
--------------------------------
Python 3.9.1
(django3) 3.1.5
django_extensions.VERSION (3, 1, 0)
 ----------------------------
import django_extensions
ModuleNotFoundError: No module named 'django_extensions'
-----------------------------
INSTALLED_APPS = [
...,
'django_extensions',
]

**Comment by trbs** [comment]
Sorry there is not enough information here to determine that...

I would say check that you installed django_extensions correctly. You can always double check with the python repl (or python) if you can import it there...

**Comment by GodCode-cpp** [comment]
same problem, I don't know what more information I can add apart from add 'django_extensions' to installed apps under settings.py causes a frozen importlib._bootstrap error that does not appear after removing said line... but I have a suspicion it might be because I am using an apple silicon chip which "at least for me" has a unique set of errors I can't put into words

**Comment by trbs** [comment]
I am using the M1 as a daily driver and haven't had this issue nor have I seen it on my Intel based Debian machine or server VM's. (Python on the M1 has been nothing but awesome🥇 for me ;-)

"Usually" there is something unrelated to Django-Extensions itself going on when this happens... If there is something we can do in Django Extensions to help I am happy to include it but for that to happen we must know exactly what is going wrong...

What would help is having something reproducible... like a set of instructions that reliable reproduces these errors, preferably as a gist on git or maybe a Dockerfile (or Ansible or Vagrant or whatever works for you ;-) ) or if it's reproducible in PyTest that would be great (so we can also include it in the standard test suite) but I am guessing it will be hard to trigger there...

I have both Intel and M1 machines with MacOS and Linux available so that shouldn't be an issue.

**Comment by ajay-aditatechnologies** [comment]
I am facing same issue

**Comment by ninex10** [comment]
hi man i have the same issue, did you find some thing ?

**Comment by quadrismegistus** [comment]
Same here, I am going insane

**Comment by ulgens** [comment]
I'll repeat this from @trbs 

> What would help is having something reproducible... like a set of instructions that reliable reproduces these errors, preferably as a gist on git or maybe a Dockerfile (or Ansible or Vagrant or whatever works for you ;-) ) or if it's reproducible in PyTest that would be great (so we can also include it in the standard test suite) but I am guessing it will be hard to trigger there...

Just saying it doesn't work doesn't help any of us 😢

**Comment by zubin** [comment]
I was stuck on this too, and resolved it like this:

```sh
$ pytest # didn't work
$ python -m pytest # worked 🎉 
```

The issue was the venv wasn't being used when calling `pytest` directly. Oddly it worked for everything else but broke when `django-extensions` was added.

**Comment by al10b** [comment]
I had the same problem here.

Looking into the directory ._venv/lib/python3.10/site-packages_ I found that the _django-extensions_ folder ist in fact called **django_extensions** (with an underline instead of a dash). 

So I simply used 
```
    'django_extensions',
```
in the settings.py file and the error message vanished.
