### ISSUE TITLE
One big app versus multiple small apps

### ISSUE THREAD

**Issue by stefan6419846** [django-extensions/django-extensions#1806]
Let's say that I want to use the *sqldiff* management command. To do so, I have to include the whole `django-extensions` app into my application. This will enable additional management commands (and other stuff) as well, which I never actually need.

Considering this and the amount of not merged PRs and open issues, I thought about whether it might make sense to split the package up into multiple smaller packages/apps which are easier/faster to maintain. Are there further opinions on this?

**Comment by Ecno92** [comment]
The ecosystem around Django comes with batteries included. In general the functionality is only provided when used, or it provides an marginal overhead. (e.g. loading the management command commands).
Unless you are running on embedded microcontrollers. I would not worry about it too much in terms of performance. 
It will indeed provide a little bit more bloated output when you call manage.py. However from my experience this is manageable. 

Splitting up the commands comes at a cost too. Either it will require us to do more configuration to enable functionality. 
(For example installing multiple apps)
If we would split up this project across multiple projects (independently maintained and packaged) it will make it harder to maintain. Especially if small non-functional aspects are going to deviate. Then you have to learn a new project every time you want to contribute. 

So my preference would be to not split the project.

**Comment by trbs** [comment]
Thanks for your interest in the project !
And happy to hear you find _sqldiff_ useful :-)

I understand where you are coming from but @Ecno92 sums it up quite nicely... splitting up will be more work for the maintainers not less. and time is currently the most limiting factor for django-extensions...

My rule of thumb is that I want as few mandatory dependencies as possible, so that installing django-extensions does not flood the python environment with dependencies that are not used. Nor that installing django-extensions slows things down (eg; due to importing or preloading stuff that is never used).

I am happy to merge patches to further those goals as well as improvements to _sqldiff_ (since that one is still a little rough as well...)

But splitting it up is not in the cards for the moment, nor is creating a python-sqldiff library (so that it could be reused by completely different projects/frameworks)...

Enjoy using django-extensions 😄
