### ISSUE TITLE
Request for New Release of django-extensions

### ISSUE THREAD

**Issue by krystofbe** [django-extensions/django-extensions#1823]
I would like to kindly request a new release of django-extensions, as the current version 3.2.1 from September 9, 2022, is now considerably outdated.

Django-extensions has been a valuable tool for the Django community, providing a wide range of useful extensions and utilities. However, as time passes, it becomes essential to keep the library up-to-date to ensure compatibility with the latest Django releases and to address any bug fixes or enhancements that have been implemented since version 3.2.1.

A new release would greatly benefit the community by incorporating recent improvements, security patches, and new features. It would also allow developers to leverage the latest advancements and maintain a smooth development experience.

**Comment by trbs** [comment]
Your absolutely right 😄 

I will try to do a new release today !
But I see some tests are failing, so need to find some time to look into it :-)

I wish I found a better way to (honestly financially) support this project, because now time keeps being a limiting factor...

If anybody reading this has demonstrable long term experience in the Django OSS community (with good standing) and willing to work together I would also be happy to add more maintainers to the project to help out.

**Comment by trbs** [comment]
https://pypi.org/project/django-extensions/3.2.3/

**Comment by krystofbe** [comment]
Thank you very much for your hard work @trbs
