### ISSUE TITLE
Question: Is using the werkzeug reloader better than Django's builtin reloader?

### ISSUE THREAD

**Issue by joeyespo** [django-extensions/django-extensions#719]
I'm wondering because I'm experiencing a delay where the browser shows a `ERR_CONNECTION_REFUSED` message when requesting a resource during a reload.

Would you lose anything from turning off the reloader and defaulting to Django's built-in one? (Or is there a technical reason that you can't actually do this?)

Using werkzeug with `runserver_plus` is incredible otherwise. Thanks!

**Comment by trbs** [comment]
I don't think we would lose anything, nothing I can think of from the top of my head anyways, if we would use Django's reloader instead of the one from Werkzeug.

Quickly looking at Django's and Werkzeugs' autoreloader code they seem similar but also far from trivial to interchange.

Could you raise this issue with the Werkzeug people ?
Probably best if any issue here gets fixed upstream.
