### ISSUE TITLE
max slug attempts exceeded AutoSlugField

### ISSUE THREAD

**Issue by pyarun** [django-extensions/django-extensions#852]
This poped in release 1.5.6

    File "/Users/arun/pyenvs/zubha1.8/lib/python2.7/site-    packages/django_extensions/db/fields/__init__.py", line 145, in slug_generator
    (original_slug, MAX_UNIQUE_QUERY_ATTEMPTS))
    RuntimeError: max slug attempts for test-org exceeded (100)

Slug generation is failing.

**Comment by gsureshb89** [comment]
i also got same issue pls solve this issue.

**Comment by trbs** [comment]
You probably have more then 100 conflicts for the `test-org` slug. (aka `test-org-100` also exists)

Happy to except PR requests to add additional modes like a random 8 char postfix instead of just sequential numbers.

In the git version you can now configure `MAX_UNIQUE_QUERY_ATTEMPTS` (default = 100) either by passing kwargs to the field or settings `EXTENSION_MAX_UNIQUE_QUERY_ATTEMPTS` in `settings.py`.

(btw if somebody wants to write a PR for unifying the way we deal with configuration options in settings.py cause that's kind of a mess right now :) )

**Comment by gsureshb89** [comment]
i added EXTENSION_MAX_UNIQUE_QUERY_ATTEMPTS in settings.py. but also getting same error
(original_slug, MAX_UNIQUE_QUERY_ATTEMPTS))
RuntimeError: max slug attempts for user-name exceeded (100)

**Comment by trbs** [comment]
are you sure you are using the github version ?

**Comment by gsureshb89** [comment]
yes

**Comment by trbs** [comment]
Commit: https://github.com/django-extensions/django-extensions/commit/30730f7212fb40eb7d9d64245a13fdcf22ada74e
```
django_extensions/db/fields/__init__.py
30:MAX_UNIQUE_QUERY_ATTEMPTS = getattr(settings, 'EXTENSIONS_MAX_UNIQUE_QUERY_ATTEMPTS', 100)
```

The setting name is `settings.EXTENSIONS_MAX_UNIQUE_QUERY_ATTEMPTS`.
Please try with that.

**Comment by gsureshb89** [comment]
i tried above code its fine working.
 thank you.

**Comment by grillazz** [comment]
Hi, 
I trying py.test but have below err 
```python
===================================================== ERRORS ======================================================
____________________________________ ERROR collecting api/tests/test_views.py _____________________________________
api/tests/test_views.py:4: in <module>
    from api.models import Station, Metering, Project
api/models.py:2: in <module>
    from django_extensions.db.fields import AutoSlugField
/usr/local/lib/python3.5/site-packages/django_extensions/db/fields/__init__.py:30: in <module>
    MAX_UNIQUE_QUERY_ATTEMPTS = getattr(settings, 'EXTENSIONS_MAX_UNIQUE_QUERY_ATTEMPTS', 100)
/usr/local/lib/python3.5/site-packages/django/conf/__init__.py:53: in __getattr__
    self._setup(name)
/usr/local/lib/python3.5/site-packages/django/conf/__init__.py:39: in _setup
    % (desc, ENVIRONMENT_VARIABLE))
E   django.core.exceptions.ImproperlyConfigured: Requested setting EXTENSIONS_MAX_UNIQUE_QUERY_ATTEMPTS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================= 1 error in 0.63 seconds =============================================```

**Comment by gsureshb89** [comment]
import settings in your test_views.py file and

EXTENSIONS_MAX_UNIQUE_QUERY_ATTEMPTS=1000 in settings.py file

**Comment by grillazz** [comment]
Solution was on `py.test ` side. Just added below to `pytest.ini` to solve this issue.
```python
[pytest]
DJANGO_SETTINGS_MODULE=EnviroMonitorWeb.settings
```

**Comment by makslevental** [comment]
resurrecting an old thing but: is there any way to set this to unlimited? i don't understand why this exists at all since, for example, if the slug is a function id i will never have a collision. so why check?

**Comment by trbs** [comment]
@makslevental is the `allow_duplicates` keyword argument a solution for you ?

If its set to `allow_duplicates=True` then `max_unique_query_attempts` is not used and the first result of the `slugify_function` should be saved.

(Maybe somebody wants to write some more extensive documentation for AutoSlugField ?)

**Comment by makslevental** [comment]
@trbs i'm confused: is the first result of the `slugify_function`, in the instance of the slug being dependent on the id, the id? if so i'm not sure what `max_unique_query_attempts1` does? certainly i don't want duplicate slugs?

**Comment by trbs** [comment]
@makslevental I had no clue what you mean with `on the id, the id?` what `id` are you talking about ? I assumed in your previous comment you want to use the Python buildin `id(...)` to generate the slug, thus saying it can never create a duplicate. While this is not true I can understand the general thought behind it. In that case `max_unique_query_attempts` should also not really bother you since it should never conflict in the database anyways, but again I can understand reasoning behind it. The use case could be that you want the database to give you a `unique contraint exception` instead of automatically creating another slug. 

Back to the original question; No there is no way to set `max_unique_query_attempts` to unlimited. 

If you want to discuss this further please open a new ticket so that we don't bother the people with notifications.
