### ISSUE TITLE
The use of auto_now and auto_now_add

### ISSUE THREAD

**Issue by snoepkast** [django-extensions/django-extensions#870]
Why was the decision made to switch from `default=datetime_now` to `auto_now=True` and `auto_now_add=True`? I found [this](https://github.com/django-extensions/django-extensions/pull/693) pull request that implements it, but it is not linked to an issue.

I create this issue now because after updating django_extensions we've run into bugs because of this. Also the use of those kwargs is discouraged and the generally accepted sollution to this problem is the way it was before the pull request was merged (using a default value and a pre_save).

Not to mention the migrations everyone has to do after updating (neglectable I know, but nevertheless unnecessary).

**Comment by trbs** [comment]
I forgot :) There has been discussions about ```auto_now``` and ```auto_now_add``` for years now.

I have no problems with changing for something better if need be as long as we are smart about it :)

Think we need to at least:
- try and be backwards compatible (give people an option to use the old values without forcing a migration)
- have a clear upgrade path (probably default to the old version with warning and then at some later point which a new version to the default)
- make sure we get it absolutely right this time and explain why that is :) 

Also looking at code like this:
```
try:
    from django.utils.timezone import now as datetime_now
    assert datetime_now
except ImportError:
    import datetime
    datetime_now = datetime.datetime.now
```

and thinking that we might need to change that too..  ```django.utils.timezone``` has been around since Django 1.4.x and defaulting to timezone less datetime is bad.

Are you willing to do some research and create a PR for this ?

**Comment by trbs** [comment]
ref: https://code.djangoproject.com/ticket/22995
