### ISSUE TITLE
Add optional packages as extras_require entries in setup.py

### ISSUE THREAD

**Issue by edmorley** [django-extensions/django-extensions#890]
A few of django-extensions' features require additional packages to be installed.

Whilst these can be installed by hand (eg `pip install django-extensions optional-dep`), allowing people to instead `pip install django-extensions[foo]` means:
1. The reason for the dependencies are clearer when reading downstream requirements files
2. Multiple linked dependencies can be bundled together + required version ranges can be updated over time. For example instead of needing to remember to `pip install pydot pyparsing==1.5.7` people could simply `pip install django-extensions[pydot]` and always get the latest compatible versions of the dependencies.

Setuptools docs can be found at:
https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

I'll open a PR for this shortly.

**Comment by trbs** [comment]
Very cool !
Looking forward to merge the PR :)

What do you recommend as labelling structure for the additional dependencies ?

Something like:

```pip install django-extensions[graph_models]``` for ```pygraphviz```, ```pydot``` and friends
```pip install django-extensions[runserver_plus]``` for ```werkzeug```, etc
```pip install django-extensions[all]``` for everything :)

Which could be kinda cool since you don't need to remember which dependencies a command has.

However there some commands with "conflicting" or "alternative" dependencies as well... ```shell_plus``` for example could have either or a combination of ```ipython```, ```bpython```, ```ptpython```, etc as dependencies.

**Comment by edmorley** [comment]
Yeah I've been trying to decide what to do in those cases myself too.
The "all" idea is a good one too. Perhaps it should just pick some sensible defaults and if people cannot install them (eg in the case of pygraphviz) then they'll just need to install `django-extensions[pydot]` manually themselves etc.

Will have a think :-)

**Comment by trbs** [comment]
Note to self: after merging PR add testenv (or similar) to tox so we can use this as tests for existance/installability of dependencies as well.

**Comment by vstoykov** [comment]
My 2 cents about `shell_plus`.

I don't think that there need to be any extra packages because:

 1. The purpose of `shell_plus` is to automatically import models and some other objects from Django in order to not to import them by hand when someone want to run the shell. This works even with plain Python shell.
 2. Default `shell` command from Django also automatically use ipython if available.
 3. Non of the extra shells are required for `shell_plus` to work (this is probably as 1. but stated differently). Other management commands needs some packages in order to work at all.

Regards!

**Comment by trbs** [comment]
Closed issue for being old / stale

**Comment by denizdogan** [comment]
I'd love it if we can make this happen somehow, but it seems like we need some sort of consensus about how it should work, right?

As far as I can tell, the extra requirements that could possibly be required are:

- shell_plus
  - bpython
  - ptpython
  - ipython
- export_emails
  - vobject
- field extensions
  - keyczar
- graph models
  - pygraphviz
  - pydot
  - pyparsing
- print_settings
  - PyYAML
- runprofileserver
  - ???
- runserverplus
  - werkzeug
- sync_s3
  - boto

I've probably missed some things, couldn't really find a good list of external dependencies so I scoured the documentation and picked up what I could make out.

I've put together a proposal below which is intentionally brash just to get a discussion going. I'd really like to get this issue resolved.

- About the shells, I think that users of this library will already have installed the shell they'd like to use, they won't install it as a extra dependency of this library.
- Keyczar is deprecated and should not be used in the first place. https://github.com/google/keyczar
- We should decide on a primary graph library to use and put that under `[graphs]`.
- I'm not sure who would print their settings using YAML, but maybe there's a use case, I don't know? Otherwise make it `[yaml]`.
- About runserverplus, I think we could just call this `[werkzeug]`.
- Users of S3 probably already have boto installed, don't make it an extras requirement.

Let me know what you think!
