### ISSUE TITLE
Filter is not working for EncryptedCharField...

### ISSUE THREAD

**Issue by Devansh3790** [django-extensions/django-extensions#949]
I have used EncryptedCharField in a model. So when i need to filter on that field it returns Blank result of queryset.

models.py
```
class Employee(models.Model)
    ssn = EncryptedCharField(max_length=11, null=True)
```

views.py
`queryset = Employee.objects.filter(ssn='123')`

Here i have a record with '123' data but queryset is alwasy blank.
Thanks in advance.

**Comment by trbs** [comment]
I don't think that's possible.

Your queryset will create a sql query like ```select * from app_employee where ssn = '123'``` but since the value of ssn is encrypted this will never match.

Since the encryption happens in Python it will be pretty hard to make SQL WHERE clauses work on that :(

A project like https://github.com/dcwatson/django-pgcrypto might be better suited for your use case. They use ```pgcrypto``` instead of ```keyczar``` and let Postgres do the crypto work including support for filtering.
